
/*
 * JDialogDebug.java
 *
 * Created on 25-juil.-2010, 12:18:27
 */

package UI;

import pimpy.*;

/**
 *
 * @author Alain
 */
public class JDialogDebug extends javax.swing.JDialog implements DebugAppender {

    private JFrameConversation mainFrame = null;

    /** Creates new form JDialogDebug */
    public JDialogDebug(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        mainFrame = (JFrameConversation) parent;
        mainFrame.getController().getDebugLogger().setDebugMode(true);
        mainFrame.getController().getDebugLogger().setAppender(this);
        mainFrame.getController().getDebugLogger().setLogToAppender(true);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDebug = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTextAreaDebug.setColumns(50);
        jTextAreaDebug.setRows(25);
        jScrollPane1.setViewportView(jTextAreaDebug);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        synchronized (this) {
            this.mainFrame.getController().getDebugLogger().setAppender(null);
        }
    }//GEN-LAST:event_formWindowClosing

    public void append(String line) {
        synchronized (this) {
            this.jTextAreaDebug.append(line);
            this.jTextAreaDebug.setCaretPosition(this.jTextAreaDebug.getText().length());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDebug;
    // End of variables declaration//GEN-END:variables

}
